export default {
    homeCircle:'home-circle',
    bookMarker:'book-variant-multiple',
    newsPaper:'newspaper-variant',
    messages:'android-messages',
    account:'card-account-details-outline',
    filter:'filter-variant',
    filterBottom:'format-align-bottom',
    filterTop:'format-align-top',
    homeMarker:'home-map-marker',
    chatMessage:'message-processing-outline',
    historyJob:'playlist-edit',
    search:'magnify',
    backArrow:'arrow-left-bold',
    heartOutline:'heart-outline',
    heart:'heart',
    starOutline:'star-outline',
    star:'star',
    phone:'phone-forward',
    circle_brightness:'brightness-1',

    face_verygood:'emoticon-kiss-outline',
    face_good:'emoticon-outline',
    face_normal:'emoticon-happy-outline',
    face_bad:'emoticon-sad-outline',
    face_sobad:'emoticon-angry-outline',

    removeTrash:'trash-can',
    tagPrice:"tag-text",
    mapCheck:'map-marker-check',
    mapMarker:'map-marker',
    fileLink:'file-link',
    send:'send',
    person:"google-street-view",

    arrowRight:'arrow-right',
    arrowLeft:'arrow-left',
    close:'close',
    arrowRightChevron:'chevron-right',

    checkboxCircleBlank:'checkbox-blank-circle-outline',
    checkboxCircleMark:'checkbox-marked-circle-outline',
    plusThick:'plus-thick',

    bell:'bell',
    cameraplus:'camera-plus-outline',
    
    facebook:'facebook',

}